services:
  postgres:
    image: 'postgres:16.3'
    environment:
      - 'POSTGRES_DB=spring_test'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5454:5432'
    networks:
      - sprint_test_network

networks:
  sprint_test_network:
    name: sprint_test_network
    driver: bridge

